import * as React from 'react';
import type { Snapshot, DomainType, ConfidenceLevel } from '@atlas/types';

interface SnapshotEmailProps {
  snapshot: Snapshot;
  email: string;
  downloadUrl: string;
}

const DOMAIN_LABELS: Record<DomainType, string> = {
  market: 'Market',
  product: 'Product',
  gtm: 'GTM',
  operations: 'Operations',
  financials: 'Financials',
};

const CONFIDENCE_COLORS: Record<ConfidenceLevel, string> = {
  high: '#16a34a',
  medium: '#d97706',
  low: '#dc2626',
};

export function SnapshotEmail({ snapshot, email, downloadUrl }: SnapshotEmailProps) {
  const generatedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return (
    <html>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Your Atlas Readiness Snapshot</title>
      </head>
      <body style={styles.body}>
        <div style={styles.container}>
          {/* Header */}
          <div style={styles.header}>
            <div style={styles.logo}>A</div>
            <h1 style={styles.title}>Your Readiness Snapshot</h1>
            <p style={styles.subtitle}>
              A summary of what you know vs. what you&apos;re assuming about U.S. expansion
            </p>
            <p style={styles.meta}>Generated for {email} on {generatedDate}</p>
          </div>

          {/* Key Findings */}
          <div style={styles.section}>
            <h2 style={styles.sectionTitle}>Key Findings</h2>
            {snapshot.key_findings.slice(0, 5).map((finding, index) => (
              <div key={index} style={styles.findingCard}>
                <p style={styles.findingText}>{finding.finding}</p>
                <div style={styles.badges}>
                  <span style={{
                    ...styles.badge,
                    backgroundColor: CONFIDENCE_COLORS[finding.confidence] + '20',
                    color: CONFIDENCE_COLORS[finding.confidence],
                  }}>
                    {finding.confidence.toUpperCase()}
                  </span>
                  <span style={styles.domainBadge}>
                    {DOMAIN_LABELS[finding.domain]}
                  </span>
                </div>
              </div>
            ))}
          </div>

          {/* Coverage Summary */}
          <div style={styles.section}>
            <h2 style={styles.sectionTitle}>Coverage Summary</h2>
            <table style={styles.coverageTable}>
              <tbody>
                {(Object.entries(snapshot.coverage_summary) as [DomainType, { high: number; medium: number; low: number }][]).map(
                  ([domain, levels]) => {
                    const total = levels.high + levels.medium + levels.low;
                    return (
                      <tr key={domain}>
                        <td style={styles.domainCell}>{DOMAIN_LABELS[domain]}</td>
                        <td style={styles.countCell}>{total} inputs</td>
                        <td style={styles.breakdownCell}>
                          <span style={{ color: CONFIDENCE_COLORS.high }}>{levels.high} high</span>
                          {' / '}
                          <span style={{ color: CONFIDENCE_COLORS.medium }}>{levels.medium} medium</span>
                          {' / '}
                          <span style={{ color: CONFIDENCE_COLORS.low }}>{levels.low} low</span>
                        </td>
                      </tr>
                    );
                  }
                )}
              </tbody>
            </table>
          </div>

          {/* Top Recommendations */}
          <div style={styles.section}>
            <h2 style={styles.sectionTitle}>Top Recommendations</h2>
            {snapshot.next_steps.slice(0, 3).map((step) => (
              <div key={step.priority} style={styles.stepCard}>
                <div style={styles.stepNumber}>{step.priority}</div>
                <div style={styles.stepContent}>
                  <p style={styles.stepAction}>{step.action}</p>
                  <p style={styles.stepRationale}>{step.rationale}</p>
                </div>
              </div>
            ))}
          </div>

          {/* Download CTA */}
          <div style={styles.ctaSection}>
            <p style={styles.ctaText}>
              Download your complete snapshot PDF for the full analysis including all strengths,
              assumptions, and gaps.
            </p>
            <a href={downloadUrl} style={styles.ctaButton}>
              Download Full PDF
            </a>
          </div>

          {/* Footer */}
          <div style={styles.footer}>
            <p style={styles.footerText}>
              Generated by Atlas Readiness Guide
            </p>
            <p style={styles.footerDisclaimer}>
              This snapshot reflects your self-reported information.
              It is not a score or recommendation to expand.
            </p>
          </div>
        </div>
      </body>
    </html>
  );
}

const styles: Record<string, React.CSSProperties> = {
  body: {
    backgroundColor: '#f8fafc',
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    margin: 0,
    padding: '20px',
  },
  container: {
    maxWidth: '600px',
    margin: '0 auto',
    backgroundColor: '#ffffff',
    borderRadius: '12px',
    overflow: 'hidden',
    boxShadow: '0 4px 6px rgba(0, 0, 0, 0.1)',
  },
  header: {
    backgroundColor: '#5754FF',
    color: '#ffffff',
    padding: '32px',
    textAlign: 'center' as const,
  },
  logo: {
    width: '48px',
    height: '48px',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: '12px',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '24px',
    fontWeight: 'bold',
    marginBottom: '16px',
    lineHeight: '48px',
  },
  title: {
    fontSize: '24px',
    fontWeight: 'bold',
    margin: '0 0 8px 0',
  },
  subtitle: {
    fontSize: '14px',
    opacity: 0.9,
    margin: '0 0 12px 0',
  },
  meta: {
    fontSize: '12px',
    opacity: 0.7,
    margin: 0,
  },
  section: {
    padding: '24px 32px',
    borderBottom: '1px solid #e2e8f0',
  },
  sectionTitle: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: '#0f172a',
    margin: '0 0 16px 0',
  },
  findingCard: {
    padding: '12px',
    backgroundColor: '#f8fafc',
    borderRadius: '8px',
    marginBottom: '12px',
  },
  findingText: {
    fontSize: '14px',
    color: '#334155',
    margin: '0 0 8px 0',
    lineHeight: '1.5',
  },
  badges: {
    display: 'flex',
    gap: '8px',
  },
  badge: {
    padding: '2px 8px',
    borderRadius: '4px',
    fontSize: '10px',
    fontWeight: 'bold',
  },
  domainBadge: {
    padding: '2px 8px',
    borderRadius: '4px',
    fontSize: '10px',
    backgroundColor: '#f1f5f9',
    color: '#64748b',
  },
  coverageTable: {
    width: '100%',
    borderCollapse: 'collapse' as const,
  },
  domainCell: {
    padding: '8px 0',
    fontSize: '14px',
    fontWeight: '500',
    color: '#0f172a',
    borderBottom: '1px solid #e2e8f0',
  },
  countCell: {
    padding: '8px 12px',
    fontSize: '14px',
    color: '#64748b',
    borderBottom: '1px solid #e2e8f0',
    textAlign: 'center' as const,
  },
  breakdownCell: {
    padding: '8px 0',
    fontSize: '12px',
    borderBottom: '1px solid #e2e8f0',
    textAlign: 'right' as const,
  },
  stepCard: {
    display: 'flex',
    marginBottom: '16px',
  },
  stepNumber: {
    width: '28px',
    height: '28px',
    backgroundColor: '#5754FF',
    color: '#ffffff',
    borderRadius: '50%',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '14px',
    fontWeight: 'bold',
    marginRight: '12px',
    flexShrink: 0,
    lineHeight: '28px',
    textAlign: 'center' as const,
  },
  stepContent: {
    flex: 1,
  },
  stepAction: {
    fontSize: '14px',
    fontWeight: '500',
    color: '#0f172a',
    margin: '0 0 4px 0',
  },
  stepRationale: {
    fontSize: '13px',
    color: '#64748b',
    margin: 0,
    lineHeight: '1.4',
  },
  ctaSection: {
    padding: '32px',
    backgroundColor: '#f8fafc',
    textAlign: 'center' as const,
  },
  ctaText: {
    fontSize: '14px',
    color: '#64748b',
    margin: '0 0 20px 0',
    lineHeight: '1.5',
  },
  ctaButton: {
    display: 'inline-block',
    padding: '12px 32px',
    backgroundColor: '#5754FF',
    color: '#ffffff',
    textDecoration: 'none',
    borderRadius: '8px',
    fontSize: '14px',
    fontWeight: '500',
  },
  footer: {
    padding: '24px 32px',
    backgroundColor: '#f1f5f9',
    textAlign: 'center' as const,
  },
  footerText: {
    fontSize: '12px',
    color: '#64748b',
    margin: '0 0 8px 0',
  },
  footerDisclaimer: {
    fontSize: '11px',
    color: '#94a3b8',
    margin: 0,
    lineHeight: '1.4',
  },
};

// Plain text version for email clients that don't support HTML
export function getPlainTextVersion(snapshot: Snapshot, email: string): string {
  const generatedDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  let text = `
YOUR ATLAS READINESS SNAPSHOT
=============================

Generated for ${email} on ${generatedDate}

KEY FINDINGS
------------
`;

  snapshot.key_findings.slice(0, 5).forEach((finding, index) => {
    text += `\n${index + 1}. ${finding.finding}\n   [${finding.confidence.toUpperCase()} confidence - ${DOMAIN_LABELS[finding.domain]}]\n`;
  });

  text += `
COVERAGE SUMMARY
----------------
`;

  (Object.entries(snapshot.coverage_summary) as [DomainType, { high: number; medium: number; low: number }][]).forEach(
    ([domain, levels]) => {
      const total = levels.high + levels.medium + levels.low;
      text += `${DOMAIN_LABELS[domain]}: ${total} inputs (${levels.high} high / ${levels.medium} medium / ${levels.low} low)\n`;
    }
  );

  text += `
TOP RECOMMENDATIONS
-------------------
`;

  snapshot.next_steps.slice(0, 3).forEach((step) => {
    text += `\n${step.priority}. ${step.action}\n   ${step.rationale}\n`;
  });

  text += `
---
Generated by Atlas Readiness Guide
This snapshot reflects your self-reported information.
It is not a score or recommendation to expand.
`;

  return text;
}
